# Generated by Django 4.2.4 on 2023-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default=1)),
            ],
            options={
                'db_table': 'tbl_supplier_mstr',
            },
        ),
    ]
