# Generated by Django 4.2.4 on 2023-09-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control_system', '0003_purchasemaster_purchasedetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasedetail',
            table=None,
        ),
    ]
