# Generated by Django 4.2.4 on 2023-09-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control_system', '0004_alter_purchasedetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasedetail',
            table='tbl_purchase_details',
        ),
    ]
