# Generated by Django 4.2.4 on 2023-09-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control_system', '0005_alter_purchasedetail_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
