# Generated by Django 4.2.4 on 2023-09-20 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control_system', '0006_alter_itemmaster_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_sale_mstr',
            },
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_control_system.itemmaster')),
                ('sale_mstr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_control_system.salemaster')),
            ],
            options={
                'db_table': 'tbl_sale_details',
            },
        ),
    ]
