# Generated by Django 4.2.4 on 2023-09-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control_system', '0007_salemaster_saledetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salemaster',
            old_name='invoice_number',
            new_name='invoice_no',
        ),
    ]
